[workspace]
members = ["echo"]

[workspace.package]
name = "rust-unix-cmd"
version = "0.1.0"
edition = "2021"
description = "Sample UNIX command line tools in Rust"

[workspace.dependencies]
clap = { version = "4.5.23", features = ["derive"] }
assert_cmd = "2.0.16"
predicates = "3.1.3"
