[package]
name = "echo"
version = "0.1.0"
edition = "2021"
description = "A simple `echo` command implementation"

[dependencies]
clap = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
